export const CATEGORIES = ["🔥 Top", "Todos", "Cacahuates", "Chips", "Gomitas", "Papas", "Bebidas"]

export const PRODUCTS = [
  { id: 1,  name: "Cacahuate Habanero", desc: "Cacahuates holandeses con el intenso sabor del chile habanero. Crujientes y picosos.", price: 15, cat: "Cacahuates", tags: ["100g"], pop: true,  spicy: false,  natural: false, emoji: "🥜", img: "/images/4.webp"  },
  { id: 2,  name: "Cacahuate Jalapeño", desc: "Cacahuates holandeses con el sabor clásico del chile jalapeño. El balance perfecto.",    price: 15, cat: "Cacahuates", tags: ["100g"], pop: false, spicy: true,  natural: false, emoji: "🥜", img: "/images/3.webp"  },
  { id: 3,  name: "Cacahuate fuego",     desc: "Cacahuates holandeses sazonados al estilo fuego. Tradicionales y llenos de sabor.",       price: 15, cat: "Cacahuates", tags: ["100g"], pop: false, spicy: false, natural: false, emoji: "🥜", img: "/images/2.webp"  },
  { id: 4,  name: "Chips de Betabel",               desc: "Chips crujientes de betabel natural. Snack saludable con sabor único y color intenso.",   price: 25, cat: "Chips",      tags: ["60g","Natural"], pop: true,  spicy: false, natural: false,  emoji: "🫚", img: "/images/6.webp"  },
  { id: 5,  name: "Chips de Jícama",                desc: "Chips de jícama ligeras y crujientes. El snack perfecto bajo en calorías.",               price: 25, cat: "Chips",      tags: ["60g","Natural"], pop: false, spicy: false, natural: false,  emoji: "🥗", img: "/images/8.webp"  },
  { id: 6,  name: "Chips de Taro",                  desc: "Chips exóticas de taro con sabor suave y textura única. Diferente y delicioso.",          price: 25, cat: "Chips",      tags: ["60g","Gourmet"], pop: false, spicy: false, natural: false,  emoji: "🫙", img: "/images/7.webp"  },
  { id: 7,  name: "Chips de Camote",                desc: "Láminas de camote natural deshidratadas. Un snack dulce-salado súper crujiente.",         price: 25, cat: "Chips",      tags: ["60g","Natural"], pop: true,  spicy: false, natural: false,  emoji: "🍠", img: "/images/19.webp" },
  { id: 8,  name: "Gomitas de Durazno",         desc: "Aros de gomita con sabor a durazno. Dulces, suaves y deliciosas.",                        price: 15, cat: "Gomitas",    tags: ["100g"], pop: false, spicy: false, natural: false, emoji: "🍑", img: "/images/9.webp"  },
  { id: 9,  name: "Gomitas Gusano Diablo",        desc: "Gusanos de gomita enchilados sabor pepino. El snack ácido-picoso que todos quieren.",     price: 15, cat: "Gomitas",    tags: ["100g"], pop: true,  spicy: false,  natural: false, emoji: "🪱", img: "/images/12.webp" },
  { id: 10, name: "Gomitas Pic-Ositos",      desc: "Ositos de gomita suaves por dentro enchilados con chile. Un clásico mexicano.",           price: 15, cat: "Gomitas",    tags: ["100g"], pop: true,  spicy: false,  natural: false, emoji: "🐻", img: "/images/11.webp" },
  { id: 11, name: "Gomitas de Tiburón",            desc: "Gomitas en forma de tiburón con sabor frutal. Divertidas y deliciosas.",                  price: 15, cat: "Gomitas",    tags: ["100g"], pop: false, spicy: false, natural: false, emoji: "🦈", img: "/images/18.webp" },
  { id: 12, name: "Papas Naturales",                  desc: "Papas fritas artesanales con sal natural. El clásico sabor crujiente de siempre.",        price: 20, cat: "Papas",      tags: ["60g"], pop: false, spicy: false, natural: false, emoji: "🥔", img: "/images/13.webp" },
  { id: 13, name: "Papas Adobadas",                  desc: "Papas sazonadas con adobo mexicano tradicional. Sabor intenso e irresistible.",           price: 20, cat: "Papas",      tags: ["60g"], pop: true,  spicy: false,  natural: false, emoji: "🌶️", img: "/images/14.webp" },
  { id: 14, name: "Papas Fuego",                    desc: "Papas con el máximo nivel de picante. Solo para los más valientes.",         price: 20, cat: "Papas",      tags: ["60g"], pop: true,  spicy: false,  natural: false, emoji: "🔥", img: "/images/15.webp" },
  { id: 15, name: "Agua de Jamaica",               desc: "Refrescante agua de jamaica natural infusionada en frío. Sin conservadores.",             price: 22, cat: "Bebidas",    tags: ["500ml","Natural"], pop: false, spicy: false, natural: false,  emoji: "🌺", img: "/images/70.webp" },
  { id: 16, name: "Mangonada",                     desc: "Deliciosa combinación de mango natural y chamoy. La bebida del verano todo el año.",      price: 30, cat: "Bebidas",    tags: ["Fresco","Frutal"], pop: true,  spicy: false,  natural: false, emoji: "🥭", img: "/images/69.webp" },
]

export type Product = (typeof PRODUCTS)[number] & { inStock?: boolean }
